### ISSUE TITLE
Use of `track!` in `bytecodec_try_decode!` macro

### ISSUE THREAD

**Issue by dagurval** [sile/bytecodec#5]
The `bytecodec_try_decode!` macro uses `track!`. When trying to use that macro in a project without the `trackable` crate, compilation fails with "error: cannot find macro `track` in this scope".

**Comment by sile** [comment]
Thank you for reaching out.
Indeed, currently, this crate highly depends on `trackable`, and the reported behavior is the intended one.
However, please let me know if it's critical to exclude `trackable` from your dependencies. I think that it's possible to make `trackable` an optional crate when I have time.

**Comment by dagurval** [comment]
I got my use of `bytecodec_try_decode`  to compile without depending directly on `trackable` by adding this dummy macro:

```
macro_rules! track {
    ($expression:expr) => {
        $expression
    };
}
```

> I think that it's possible to make trackable an optional crate when I have time.

Not necessary :-)

**Comment by sile** [comment]
Nice workaround! Thanks!
